drop table if exists batch_job_execution_context;
drop table if exists batch_job_execution_params;
drop table if exists batch_job_execution_seq;
drop table if exists batch_job_seq;
drop table if exists batch_step_execution_context;
drop table if exists batch_step_execution_seq;
drop table if exists batch_step_execution;
drop table if exists batch_job_execution;
drop table if exists batch_job_instance;
