package com.ecard.core.model;
// Generated Aug 31, 2015 2:01:59 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActionLogId generated by hbm2java
 */
@Embeddable
public class ActionLogId  implements java.io.Serializable {


     private int userId;
     private int actionType;
     private String actionMessage;
     private Date actionDate;

    public ActionLogId() {
    }

	
    public ActionLogId(int userId, int actionType, Date actionDate) {
        this.userId = userId;
        this.actionType = actionType;
        this.actionDate = actionDate;
    }
    public ActionLogId(int userId, int actionType, String actionMessage, Date actionDate) {
       this.userId = userId;
       this.actionType = actionType;
       this.actionMessage = actionMessage;
       this.actionDate = actionDate;
    }
   


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="action_type", nullable=false)
    public int getActionType() {
        return this.actionType;
    }
    
    public void setActionType(int actionType) {
        this.actionType = actionType;
    }


    @Column(name="action_message", length=65535)
    public String getActionMessage() {
        return this.actionMessage;
    }
    
    public void setActionMessage(String actionMessage) {
        this.actionMessage = actionMessage;
    }


    @Column(name="action_date", nullable=false, length=19)
    public Date getActionDate() {
        return this.actionDate;
    }
    
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ActionLogId) ) return false;
		 ActionLogId castOther = ( ActionLogId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getActionType()==castOther.getActionType())
 && ( (this.getActionMessage()==castOther.getActionMessage()) || ( this.getActionMessage()!=null && castOther.getActionMessage()!=null && this.getActionMessage().equals(castOther.getActionMessage()) ) )
 && ( (this.getActionDate()==castOther.getActionDate()) || ( this.getActionDate()!=null && castOther.getActionDate()!=null && this.getActionDate().equals(castOther.getActionDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getActionType();
         result = 37 * result + ( getActionMessage() == null ? 0 : this.getActionMessage().hashCode() );
         result = 37 * result + ( getActionDate() == null ? 0 : this.getActionDate().hashCode() );
         return result;
   }   


}


