package com.ecard.core.model;
// Generated Aug 31, 2015 2:01:59 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActionLog generated by hbm2java
 */
@Entity
@Table(name="action_log"
)
public class ActionLog  implements java.io.Serializable {


     private ActionLogId id;
     private UserInfo userInfo;

    public ActionLog() {
    }

    public ActionLog(ActionLogId id, UserInfo userInfo) {
       this.id = id;
       this.userInfo = userInfo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="actionType", column=@Column(name="action_type", nullable=false) ), 
        @AttributeOverride(name="actionMessage", column=@Column(name="action_message", length=65535) ), 
        @AttributeOverride(name="actionDate", column=@Column(name="action_date", nullable=false, length=19) ) } )
    public ActionLogId getId() {
        return this.id;
    }
    
    public void setId(ActionLogId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }




}


