package com.ecard.core.model;
// Generated Sep 11, 2015 9:57:46 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdminPossessionCardId generated by hbm2java
 */
@Embeddable
public class AdminPossessionCardId  implements java.io.Serializable {


     private Integer userId;
     private int cardId;
     private Date createDate;

    public AdminPossessionCardId() {
    }

	
    public AdminPossessionCardId(int cardId) {
        this.cardId = cardId;
    }
    public AdminPossessionCardId(Integer userId, int cardId, Date createDate) {
       this.userId = userId;
       this.cardId = cardId;
       this.createDate = createDate;
    }
   


    @Column(name="user_id")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }


    @Column(name="card_id", nullable=false)
    public int getCardId() {
        return this.cardId;
    }
    
    public void setCardId(int cardId) {
        this.cardId = cardId;
    }


    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdminPossessionCardId) ) return false;
		 AdminPossessionCardId castOther = ( AdminPossessionCardId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && (this.getCardId()==castOther.getCardId())
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + this.getCardId();
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         return result;
   }   


}


