package com.ecard.core.model;
// Generated Aug 4, 2015 10:15:08 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;



/**
 * AutoLogin generated by hbm2java
 */
@Entity
@Table(name="auto_login"
)
public class AutoLogin  implements java.io.Serializable {


     private Integer loginId;
     private UserInfo userInfo;
     private String token;
     private Date createDate;

    public AutoLogin() {
    }

	
    public AutoLogin(UserInfo userInfo, Date createDate) {
        this.userInfo = userInfo;
        this.createDate = createDate;
    }
    public AutoLogin(UserInfo userInfo, String token, Date createDate) {
       this.userInfo = userInfo;
       this.token = token;
       this.createDate = createDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="login_id", unique=true, nullable=false)
    public Integer getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }

    
    @Column(name="token", length=65535)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }

    
    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


