package com.ecard.core.model;
// Generated Aug 4, 2015 10:15:08 AM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CardTagId generated by hbm2java
 */
@Embeddable
public class CardTagId  implements java.io.Serializable {


     private int cardId;
     private int tagId;

    public CardTagId() {
    }

    public CardTagId(int cardId, int tagId) {
       this.cardId = cardId;
       this.tagId = tagId;
    }
   


    @Column(name="card_id", nullable=false)
    public int getCardId() {
        return this.cardId;
    }
    
    public void setCardId(int cardId) {
        this.cardId = cardId;
    }


    @Column(name="tag_id", nullable=false)
    public int getTagId() {
        return this.tagId;
    }
    
    public void setTagId(int tagId) {
        this.tagId = tagId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CardTagId) ) return false;
		 CardTagId castOther = ( CardTagId ) other; 
         
		 return (this.getCardId()==castOther.getCardId())
 && (this.getTagId()==castOther.getTagId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCardId();
         result = 37 * result + this.getTagId();
         return result;
   }   


}


