package com.ecard.core.model;
// Generated Oct 14, 2015 9:55:15 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CardUpdateHistoryId generated by hbm2java
 */
@Embeddable
public class CardUpdateHistoryId  implements java.io.Serializable {


     private int cardId;
     private int paramType;
     private String oldData;
     private String newData;
     private Date createDate;
     private Date updateDate;
     private int operaterId;

    public CardUpdateHistoryId() {
    }

	
    public CardUpdateHistoryId(int cardId, int paramType, Date createDate, Date updateDate, int operaterId) {
        this.cardId = cardId;
        this.paramType = paramType;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.operaterId = operaterId;
    }
    public CardUpdateHistoryId(int cardId, int paramType, String oldData, String newData, Date createDate, Date updateDate, int operaterId) {
       this.cardId = cardId;
       this.paramType = paramType;
       this.oldData = oldData;
       this.newData = newData;
       this.createDate = createDate;
       this.updateDate = updateDate;
       this.operaterId = operaterId;
    }
   


    @Column(name="card_id", nullable=false)
    public int getCardId() {
        return this.cardId;
    }
    
    public void setCardId(int cardId) {
        this.cardId = cardId;
    }


    @Column(name="param_type", nullable=false)
    public int getParamType() {
        return this.paramType;
    }
    
    public void setParamType(int paramType) {
        this.paramType = paramType;
    }


    @Column(name="old_data", length=65535)
    public String getOldData() {
        return this.oldData;
    }
    
    public void setOldData(String oldData) {
        this.oldData = oldData;
    }


    @Column(name="new_data", length=65535)
    public String getNewData() {
        return this.newData;
    }
    
    public void setNewData(String newData) {
        this.newData = newData;
    }


    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }


    @Column(name="update_date", nullable=false, length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }


    @Column(name="operater_id", nullable=false)
    public int getOperaterId() {
        return this.operaterId;
    }
    
    public void setOperaterId(int operaterId) {
        this.operaterId = operaterId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CardUpdateHistoryId) ) return false;
		 CardUpdateHistoryId castOther = ( CardUpdateHistoryId ) other; 
         
		 return (this.getCardId()==castOther.getCardId())
 && (this.getParamType()==castOther.getParamType())
 && ( (this.getOldData()==castOther.getOldData()) || ( this.getOldData()!=null && castOther.getOldData()!=null && this.getOldData().equals(castOther.getOldData()) ) )
 && ( (this.getNewData()==castOther.getNewData()) || ( this.getNewData()!=null && castOther.getNewData()!=null && this.getNewData().equals(castOther.getNewData()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getUpdateDate()==castOther.getUpdateDate()) || ( this.getUpdateDate()!=null && castOther.getUpdateDate()!=null && this.getUpdateDate().equals(castOther.getUpdateDate()) ) )
 && (this.getOperaterId()==castOther.getOperaterId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCardId();
         result = 37 * result + this.getParamType();
         result = 37 * result + ( getOldData() == null ? 0 : this.getOldData().hashCode() );
         result = 37 * result + ( getNewData() == null ? 0 : this.getNewData().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         result = 37 * result + ( getUpdateDate() == null ? 0 : this.getUpdateDate().hashCode() );
         result = 37 * result + this.getOperaterId();
         return result;
   }   


}


