package com.ecard.core.model;
// Generated Aug 4, 2015 10:15:08 AM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CardTag generated by hbm2java
 */
@Entity
@Table(name="card_tag"
)
public class CardTag  implements java.io.Serializable {


     private CardTagId id;
     private CardInfo cardInfo;
     private UserTag userTag;

    public CardTag() {
    }

    public CardTag(CardTagId id, CardInfo cardInfo, UserTag userTag) {
       this.id = id;
       this.cardInfo = cardInfo;
       this.userTag = userTag;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cardId", column=@Column(name="card_id", nullable=false) ), 
        @AttributeOverride(name="tagId", column=@Column(name="tag_id", nullable=false) ) } )
    public CardTagId getId() {
        return this.id;
    }
    
    public void setId(CardTagId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="card_id", nullable=false, insertable=false, updatable=false)
    public CardInfo getCardInfo() {
        return this.cardInfo;
    }
    
    public void setCardInfo(CardInfo cardInfo) {
        this.cardInfo = cardInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tag_id", nullable=false, insertable=false, updatable=false)
    public UserTag getUserTag() {
        return this.userTag;
    }
    
    public void setUserTag(UserTag userTag) {
        this.userTag = userTag;
    }




}


