package com.ecard.core.model;
// Generated Aug 4, 2015 10:15:08 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;



/**
 * CompanyInfo generated by hbm2java
 */
@Entity
@Table(name="company_info"
)
public class CompanyInfo  implements java.io.Serializable {


     private Integer companyId;
     private String companyName;
     private String companyNameKana;
     private Date createDate;
     private Date updateDate;
     private int operaterId;
     private Set<CardInfo> cardInfos = new HashSet<CardInfo>(0);

    public CompanyInfo() {
    }

	
    public CompanyInfo(String companyName, String companyNameKana, Date createDate, int operaterId) {
        this.companyName = companyName;
        this.companyNameKana = companyNameKana;
        this.createDate = createDate;
        this.operaterId = operaterId;
    }
    public CompanyInfo(String companyName, String companyNameKana, Date createDate, Date updateDate, int operaterId, Set<CardInfo> cardInfos) {
       this.companyName = companyName;
       this.companyNameKana = companyNameKana;
       this.createDate = createDate;
       this.updateDate = updateDate;
       this.operaterId = operaterId;
       this.cardInfos = cardInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="company_id", unique=true, nullable=false)
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="company_name", nullable=false, length=65535)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    
    @Column(name="company_name_kana", nullable=false, length=65535)
    public String getCompanyNameKana() {
        return this.companyNameKana;
    }
    
    public void setCompanyNameKana(String companyNameKana) {
        this.companyNameKana = companyNameKana;
    }

    
    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="operater_id", nullable=false)
    public int getOperaterId() {
        return this.operaterId;
    }
    
    public void setOperaterId(int operaterId) {
        this.operaterId = operaterId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="companyInfo")
    public Set<CardInfo> getCardInfos() {
        return this.cardInfos;
    }
    
    public void setCardInfos(Set<CardInfo> cardInfos) {
        this.cardInfos = cardInfos;
    }




}


