package com.ecard.core.model;
// Generated Aug 4, 2015 10:15:08 AM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContactHistory generated by hbm2java
 */
@Entity
@Table(name="contact_history"
)
public class ContactHistory  implements java.io.Serializable {


     private ContactHistoryId id;
     private CardInfo cardInfo;

    public ContactHistory() {
    }

    public ContactHistory(ContactHistoryId id, CardInfo cardInfo) {
       this.id = id;
       this.cardInfo = cardInfo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cardId", column=@Column(name="card_id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="contactDate", column=@Column(name="contact_date", length=19) ), 
        @AttributeOverride(name="title", column=@Column(name="title", length=65535) ), 
        @AttributeOverride(name="place", column=@Column(name="place", length=65535) ), 
        @AttributeOverride(name="contactMemo", column=@Column(name="contact_memo", length=65535) ) } )
    public ContactHistoryId getId() {
        return this.id;
    }
    
    public void setId(ContactHistoryId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="card_id", nullable=false, insertable=false, updatable=false)
    public CardInfo getCardInfo() {
        return this.cardInfo;
    }
    
    public void setCardInfo(CardInfo cardInfo) {
        this.cardInfo = cardInfo;
    }




}


