package com.ecard.core.model;
// Generated Aug 4, 2015 10:15:08 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContactHistoryId generated by hbm2java
 */
@Embeddable
public class ContactHistoryId  implements java.io.Serializable {


     private int cardId;
     private int userId;
     private Date contactDate;
     private String title;
     private String place;
     private String contactMemo;

    public ContactHistoryId() {
    }

	
    public ContactHistoryId(int cardId, int userId) {
        this.cardId = cardId;
        this.userId = userId;
    }
    public ContactHistoryId(int cardId, int userId, Date contactDate, String title, String place, String contactMemo) {
       this.cardId = cardId;
       this.userId = userId;
       this.contactDate = contactDate;
       this.title = title;
       this.place = place;
       this.contactMemo = contactMemo;
    }
   


    @Column(name="card_id", nullable=false)
    public int getCardId() {
        return this.cardId;
    }
    
    public void setCardId(int cardId) {
        this.cardId = cardId;
    }


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="contact_date", length=19)
    public Date getContactDate() {
        return this.contactDate;
    }
    
    public void setContactDate(Date contactDate) {
        this.contactDate = contactDate;
    }


    @Column(name="title", length=65535)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }


    @Column(name="place", length=65535)
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }


    @Column(name="contact_memo", length=65535)
    public String getContactMemo() {
        return this.contactMemo;
    }
    
    public void setContactMemo(String contactMemo) {
        this.contactMemo = contactMemo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContactHistoryId) ) return false;
		 ContactHistoryId castOther = ( ContactHistoryId ) other; 
         
		 return (this.getCardId()==castOther.getCardId())
 && (this.getUserId()==castOther.getUserId())
 && ( (this.getContactDate()==castOther.getContactDate()) || ( this.getContactDate()!=null && castOther.getContactDate()!=null && this.getContactDate().equals(castOther.getContactDate()) ) )
 && ( (this.getTitle()==castOther.getTitle()) || ( this.getTitle()!=null && castOther.getTitle()!=null && this.getTitle().equals(castOther.getTitle()) ) )
 && ( (this.getPlace()==castOther.getPlace()) || ( this.getPlace()!=null && castOther.getPlace()!=null && this.getPlace().equals(castOther.getPlace()) ) )
 && ( (this.getContactMemo()==castOther.getContactMemo()) || ( this.getContactMemo()!=null && castOther.getContactMemo()!=null && this.getContactMemo().equals(castOther.getContactMemo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCardId();
         result = 37 * result + this.getUserId();
         result = 37 * result + ( getContactDate() == null ? 0 : this.getContactDate().hashCode() );
         result = 37 * result + ( getTitle() == null ? 0 : this.getTitle().hashCode() );
         result = 37 * result + ( getPlace() == null ? 0 : this.getPlace().hashCode() );
         result = 37 * result + ( getContactMemo() == null ? 0 : this.getContactMemo().hashCode() );
         return result;
   }   


}


