package com.ecard.core.model;
// Generated Sep 30, 2015 8:05:25 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DataIndex generated by hbm2java
 */
@Entity
@Table(name="data_index"
)
public class DataIndex  implements java.io.Serializable {


     private DataIndexId id;

    public DataIndex() {
    }

    public DataIndex(DataIndexId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="indexType", column=@Column(name="index_type", nullable=false) ), 
        @AttributeOverride(name="indexNo", column=@Column(name="index_no", nullable=false, length=65535) ), 
        @AttributeOverride(name="createDate", column=@Column(name="create_date", nullable=false, length=19) ) } )
    public DataIndexId getId() {
        return this.id;
    }
    
    public void setId(DataIndexId id) {
        this.id = id;
    }




}


