package com.ecard.core.model;
// Generated Sep 10, 2015 2:34:27 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DataIndexId generated by hbm2java
 */
@Embeddable
public class DataIndexId  implements java.io.Serializable {


     private int indexType;
     private String indexNo;
     private Date createDate;

    public DataIndexId() {
    }

    public DataIndexId(int indexType, String indexNo, Date createDate) {
       this.indexType = indexType;
       this.indexNo = indexNo;
       this.createDate = createDate;
    }
   


    @Column(name="index_type", nullable=false)
    public int getIndexType() {
        return this.indexType;
    }
    
    public void setIndexType(int indexType) {
        this.indexType = indexType;
    }


    @Column(name="index_no", nullable=false, length=65535)
    public String getIndexNo() {
        return this.indexNo;
    }
    
    public void setIndexNo(String indexNo) {
        this.indexNo = indexNo;
    }


    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DataIndexId) ) return false;
		 DataIndexId castOther = ( DataIndexId ) other; 
         
		 return (this.getIndexType()==castOther.getIndexType())
 && ( (this.getIndexNo()==castOther.getIndexNo()) || ( this.getIndexNo()!=null && castOther.getIndexNo()!=null && this.getIndexNo().equals(castOther.getIndexNo()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIndexType();
         result = 37 * result + ( getIndexNo() == null ? 0 : this.getIndexNo().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         return result;
   }   


}


