package com.ecard.core.model;
// Generated Aug 22, 2015 3:13:51 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupCompanyDepartmentId generated by hbm2java
 */
@Embeddable
public class GroupCompanyDepartmentId  implements java.io.Serializable {


     private int groupCompanyId;
     private String groupCompanyDepartmentName;
     private int seq;

    public GroupCompanyDepartmentId() {
    }

    public GroupCompanyDepartmentId(int groupCompanyId, String groupCompanyDepartmentName, int seq) {
       this.groupCompanyId = groupCompanyId;
       this.groupCompanyDepartmentName = groupCompanyDepartmentName;
       this.seq = seq;
    }
   


    @Column(name="group_company_id", nullable=false)
    public int getGroupCompanyId() {
        return this.groupCompanyId;
    }
    
    public void setGroupCompanyId(int groupCompanyId) {
        this.groupCompanyId = groupCompanyId;
    }


    @Column(name="group_company_department_name", nullable=false)
    public String getGroupCompanyDepartmentName() {
        return this.groupCompanyDepartmentName;
    }
    
    public void setGroupCompanyDepartmentName(String groupCompanyDepartmentName) {
        this.groupCompanyDepartmentName = groupCompanyDepartmentName;
    }


    @Column(name="seq", nullable=false)
    public int getSeq() {
        return this.seq;
    }
    
    public void setSeq(int seq) {
        this.seq = seq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GroupCompanyDepartmentId) ) return false;
		 GroupCompanyDepartmentId castOther = ( GroupCompanyDepartmentId ) other; 
         
		 return (this.getGroupCompanyId()==castOther.getGroupCompanyId())
 && (this.getGroupCompanyDepartmentName()==castOther.getGroupCompanyDepartmentName())
 && (this.getSeq()==castOther.getSeq());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGroupCompanyId();
         result = 37 * result + this.getSeq();
         return result;
   }   


}


