package com.ecard.core.model;
// Generated Aug 22, 2015 3:13:51 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;



/**
 * GroupCompanyInfo generated by hbm2java
 */
@Entity
@Table(name="group_company_info"
)
public class GroupCompanyInfo  implements java.io.Serializable {


     private Integer groupCompanyId;
     private String groupCompanyName;
     private String groupCompanyNameKana;
     private Date createDate;
     private Date updateDate;
     private Integer operaterId;
     private Set<GroupCompanyDepartment> groupCompanyDepartments = new HashSet<GroupCompanyDepartment>(0);

    public GroupCompanyInfo() {
    }

	
    public GroupCompanyInfo(String groupCompanyNameKana, Date createDate) {
        this.groupCompanyNameKana = groupCompanyNameKana;
        this.createDate = createDate;
    }
    public GroupCompanyInfo(String groupCompanyName, String groupCompanyNameKana, Date createDate, Date updateDate, Integer operaterId, Set<GroupCompanyDepartment> groupCompanyDepartments) {
       this.groupCompanyName = groupCompanyName;
       this.groupCompanyNameKana = groupCompanyNameKana;
       this.createDate = createDate;
       this.updateDate = updateDate;
       this.operaterId = operaterId;
       this.groupCompanyDepartments = groupCompanyDepartments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="group_company_id", unique=true, nullable=false)
    public Integer getGroupCompanyId() {
        return this.groupCompanyId;
    }
    
    public void setGroupCompanyId(Integer groupCompanyId) {
        this.groupCompanyId = groupCompanyId;
    }

    
    @Column(name="group_company_name")
    public String getGroupCompanyName() {
        return this.groupCompanyName;
    }
    
    public void setGroupCompanyName(String groupCompanyName) {
        this.groupCompanyName = groupCompanyName;
    }

    
    @Column(name="group_company_name_kana", length=65535)
    public String getGroupCompanyNameKana() {
        return this.groupCompanyNameKana;
    }
    
    public void setGroupCompanyNameKana(String groupCompanyNameKana) {
        this.groupCompanyNameKana = groupCompanyNameKana;
    }

    
    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="operater_id")
    public Integer getOperaterId() {
        return this.operaterId;
    }
    
    public void setOperaterId(Integer operaterId) {
        this.operaterId = operaterId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groupCompanyInfo")
    public Set<GroupCompanyDepartment> getGroupCompanyDepartments() {
        return this.groupCompanyDepartments;
    }
    
    public void setGroupCompanyDepartments(Set<GroupCompanyDepartment> groupCompanyDepartments) {
        this.groupCompanyDepartments = groupCompanyDepartments;
    }




}


