package com.ecard.core.model;
// Generated Aug 8, 2015 9:56:13 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;



/**
 * HelpInfo generated by hbm2java
 */
@Entity
@Table(name="help_info"
)
public class HelpInfo  implements java.io.Serializable {


     private Integer helpId;
     private String title;
     private String mainText;
     private Date noticeDate;
     private Integer seq;
     private Date createDate;
     private Integer deleteFlg;
     private Date deleteDate;

    public HelpInfo() {
    }

    public HelpInfo(String title, String mainText, Date noticeDate, Integer seq, Date createDate, Integer deleteFlg, Date deleteDate) {
       this.title = title;
       this.mainText = mainText;
       this.noticeDate = noticeDate;
       this.seq = seq;
       this.createDate = createDate;
       this.deleteFlg = deleteFlg;
       this.deleteDate = deleteDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="help_id", unique=true, nullable=false)
    public Integer getHelpId() {
        return this.helpId;
    }
    
    public void setHelpId(Integer helpId) {
        this.helpId = helpId;
    }

    
    @Column(name="title", length=65535)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="main_text", length=65535)
    public String getMainText() {
        return this.mainText;
    }
    
    public void setMainText(String mainText) {
        this.mainText = mainText;
    }

    
    @Column(name="notice_date", length=19)
    public Date getNoticeDate() {
        return this.noticeDate;
    }
    
    public void setNoticeDate(Date noticeDate) {
        this.noticeDate = noticeDate;
    }

    
    @Column(name="seq")
    public Integer getSeq() {
        return this.seq;
    }
    
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="delete_flg")
    public Integer getDeleteFlg() {
        return this.deleteFlg;
    }
    
    public void setDeleteFlg(Integer deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    
    @Column(name="delete_date", length=19)
    public Date getDeleteDate() {
        return this.deleteDate;
    }
    
    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }




}


