package com.ecard.core.model;
// Generated Sep 18, 2015 11:26:46 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;



/**
 * HistorySendEmail generated by hbm2java
 */
@Entity
@Table(name="history_send_email"
)
public class HistorySendEmail  implements java.io.Serializable {


     private Integer id;
     private String userSendTo;
     private String mailTitle;
     private String mailDetail;
     private int sendType;
     private Date createDate;

    public HistorySendEmail() {
    }

	
    public HistorySendEmail(int sendType) {
        this.sendType = sendType;
    }
    public HistorySendEmail(String userSendTo, String mailTitle, String mailDetail, int sendType, Date createDate) {
       this.userSendTo = userSendTo;
       this.mailTitle = mailTitle;
       this.mailDetail = mailDetail;
       this.sendType = sendType;
       this.createDate = createDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="user_send_to", length=65535)
    public String getUserSendTo() {
        return this.userSendTo;
    }
    
    public void setUserSendTo(String userSendTo) {
        this.userSendTo = userSendTo;
    }

    
    @Column(name="mail_title", length=65535)
    public String getMailTitle() {
        return this.mailTitle;
    }
    
    public void setMailTitle(String mailTitle) {
        this.mailTitle = mailTitle;
    }

    
    @Column(name="mail_detail", length=65535)
    public String getMailDetail() {
        return this.mailDetail;
    }
    
    public void setMailDetail(String mailDetail) {
        this.mailDetail = mailDetail;
    }

    
    @Column(name="send_type", nullable=false)
    public int getSendType() {
        return this.sendType;
    }
    
    public void setSendType(int sendType) {
        this.sendType = sendType;
    }

    
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


