package com.ecard.core.model;
// Generated Aug 4, 2015 10:15:08 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;



/**
 * InquiryInfo generated by hbm2java
 */
@Entity
@Table(name="inquiry_info"
)
public class InquiryInfo  implements java.io.Serializable {


     private Integer inquiryId;
     private UserInfo userInfo;
     private int inquiryType;
     private String title;
     private String inquiryText;
     private int answerFlg;
     private String answerText;
     private Date createDate;
     private Date updateDate;
     private int operaterId;

    public InquiryInfo() {
    }

	
    public InquiryInfo(UserInfo userInfo, int inquiryType, String title, String inquiryText, int answerFlg, Date createDate, int operaterId) {
        this.userInfo = userInfo;
        this.inquiryType = inquiryType;
        this.title = title;
        this.inquiryText = inquiryText;
        this.answerFlg = answerFlg;
        this.createDate = createDate;
        this.operaterId = operaterId;
    }
    public InquiryInfo(UserInfo userInfo, int inquiryType, String title, String inquiryText, int answerFlg, String answerText, Date createDate, Date updateDate, int operaterId) {
       this.userInfo = userInfo;
       this.inquiryType = inquiryType;
       this.title = title;
       this.inquiryText = inquiryText;
       this.answerFlg = answerFlg;
       this.answerText = answerText;
       this.createDate = createDate;
       this.updateDate = updateDate;
       this.operaterId = operaterId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="inquiry_id", unique=true, nullable=false)
    public Integer getInquiryId() {
        return this.inquiryId;
    }
    
    public void setInquiryId(Integer inquiryId) {
        this.inquiryId = inquiryId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }

    
    @Column(name="inquiry_type", nullable=false)
    public int getInquiryType() {
        return this.inquiryType;
    }
    
    public void setInquiryType(int inquiryType) {
        this.inquiryType = inquiryType;
    }

    
    @Column(name="title", nullable=false, length=65535)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="inquiry_text", nullable=false, length=65535)
    public String getInquiryText() {
        return this.inquiryText;
    }
    
    public void setInquiryText(String inquiryText) {
        this.inquiryText = inquiryText;
    }

    
    @Column(name="answer_flg", nullable=false)
    public int getAnswerFlg() {
        return this.answerFlg;
    }
    
    public void setAnswerFlg(int answerFlg) {
        this.answerFlg = answerFlg;
    }

    
    @Column(name="answer_text", length=65535)
    public String getAnswerText() {
        return this.answerText;
    }
    
    public void setAnswerText(String answerText) {
        this.answerText = answerText;
    }

    
    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="operater_id", nullable=false)
    public int getOperaterId() {
        return this.operaterId;
    }
    
    public void setOperaterId(int operaterId) {
        this.operaterId = operaterId;
    }




}


