package com.ecard.core.model;
// Generated Oct 14, 2015 9:32:56 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LinkCardId generated by hbm2java
 */
@Embeddable
public class LinkCardId  implements java.io.Serializable {


     private int cardId;
     private Integer cardOwnerId;
     private String imageFile;
     private String companyName;
     private String departmentName;
     private String name;
     private Date createDate1;
     private Date createDate2;

    public LinkCardId() {
    }

	
    public LinkCardId(int cardId, String imageFile, String companyName, String departmentName, String name, Date createDate1, Date createDate2) {
        this.cardId = cardId;
        this.imageFile = imageFile;
        this.companyName = companyName;
        this.departmentName = departmentName;
        this.name = name;
        this.createDate1 = createDate1;
        this.createDate2 = createDate2;
    }
    public LinkCardId(int cardId, Integer cardOwnerId, String imageFile, String companyName, String departmentName, String name, Date createDate1, Date createDate2) {
       this.cardId = cardId;
       this.cardOwnerId = cardOwnerId;
       this.imageFile = imageFile;
       this.companyName = companyName;
       this.departmentName = departmentName;
       this.name = name;
       this.createDate1 = createDate1;
       this.createDate2 = createDate2;
    }
   


    @Column(name="card_id", nullable=false)
    public int getCardId() {
        return this.cardId;
    }
    
    public void setCardId(int cardId) {
        this.cardId = cardId;
    }


    @Column(name="card_owner_id")
    public Integer getCardOwnerId() {
        return this.cardOwnerId;
    }
    
    public void setCardOwnerId(Integer cardOwnerId) {
        this.cardOwnerId = cardOwnerId;
    }


    @Column(name="image_file", nullable=false, length=65535)
    public String getImageFile() {
        return this.imageFile;
    }
    
    public void setImageFile(String imageFile) {
        this.imageFile = imageFile;
    }


    @Column(name="company_name", nullable=false, length=65535)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }


    @Column(name="department_name", nullable=false, length=65535)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }


    @Column(name="name", nullable=false, length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


    @Column(name="create_date_1", nullable=false, length=19)
    public Date getCreateDate1() {
        return this.createDate1;
    }
    
    public void setCreateDate1(Date createDate1) {
        this.createDate1 = createDate1;
    }


    @Column(name="create_date_2", nullable=false, length=19)
    public Date getCreateDate2() {
        return this.createDate2;
    }
    
    public void setCreateDate2(Date createDate2) {
        this.createDate2 = createDate2;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LinkCardId) ) return false;
		 LinkCardId castOther = ( LinkCardId ) other; 
         
		 return (this.getCardId()==castOther.getCardId())
 && ( (this.getCardOwnerId()==castOther.getCardOwnerId()) || ( this.getCardOwnerId()!=null && castOther.getCardOwnerId()!=null && this.getCardOwnerId().equals(castOther.getCardOwnerId()) ) )
 && ( (this.getImageFile()==castOther.getImageFile()) || ( this.getImageFile()!=null && castOther.getImageFile()!=null && this.getImageFile().equals(castOther.getImageFile()) ) )
 && ( (this.getCompanyName()==castOther.getCompanyName()) || ( this.getCompanyName()!=null && castOther.getCompanyName()!=null && this.getCompanyName().equals(castOther.getCompanyName()) ) )
 && ( (this.getDepartmentName()==castOther.getDepartmentName()) || ( this.getDepartmentName()!=null && castOther.getDepartmentName()!=null && this.getDepartmentName().equals(castOther.getDepartmentName()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getCreateDate1()==castOther.getCreateDate1()) || ( this.getCreateDate1()!=null && castOther.getCreateDate1()!=null && this.getCreateDate1().equals(castOther.getCreateDate1()) ) )
 && ( (this.getCreateDate2()==castOther.getCreateDate2()) || ( this.getCreateDate2()!=null && castOther.getCreateDate2()!=null && this.getCreateDate2().equals(castOther.getCreateDate2()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCardId();
         result = 37 * result + ( getCardOwnerId() == null ? 0 : this.getCardOwnerId().hashCode() );
         result = 37 * result + ( getImageFile() == null ? 0 : this.getImageFile().hashCode() );
         result = 37 * result + ( getCompanyName() == null ? 0 : this.getCompanyName().hashCode() );
         result = 37 * result + ( getDepartmentName() == null ? 0 : this.getDepartmentName().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getCreateDate1() == null ? 0 : this.getCreateDate1().hashCode() );
         result = 37 * result + ( getCreateDate2() == null ? 0 : this.getCreateDate2().hashCode() );
         return result;
   }   


}


