package com.ecard.core.model;
// Generated Oct 19, 2015 8:43:20 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;



/**
 * MailDomainList generated by hbm2java
 */
@Entity
@Table(name="mail_domain_list"
)
public class MailDomainList  implements java.io.Serializable {


     private Integer mailDomainId;
     private String mailDomain;
     private Date createDate;

    public MailDomainList() {
    }

	
    public MailDomainList(String mailDomain) {
        this.mailDomain = mailDomain;
    }
    public MailDomainList(String mailDomain, Date createDate) {
       this.mailDomain = mailDomain;
       this.createDate = createDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mail_domain_id", unique=true, nullable=false)
    public Integer getMailDomainId() {
        return this.mailDomainId;
    }
    
    public void setMailDomainId(Integer mailDomainId) {
        this.mailDomainId = mailDomainId;
    }

    
    @Column(name="mail_domain", nullable=false, length=65535)
    public String getMailDomain() {
        return this.mailDomain;
    }
    
    public void setMailDomain(String mailDomain) {
        this.mailDomain = mailDomain;
    }

    
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


