package com.ecard.core.model;
// Generated Oct 14, 2015 5:55:51 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OldCardId generated by hbm2java
 */
@Embeddable
public class OldCardId  implements java.io.Serializable {


     private int cardId;
     private int oldCardId;
     private int cardOwnerId;
     private int seq;

    public OldCardId() {
    }

    public OldCardId(int cardId, int oldCardId, int cardOwnerId, int seq) {
       this.cardId = cardId;
       this.oldCardId = oldCardId;
       this.cardOwnerId = cardOwnerId;
       this.seq = seq;
    }
   


    @Column(name="card_id", nullable=false)
    public int getCardId() {
        return this.cardId;
    }
    
    public void setCardId(int cardId) {
        this.cardId = cardId;
    }


    @Column(name="old_card_id", nullable=false)
    public int getOldCardId() {
        return this.oldCardId;
    }
    
    public void setOldCardId(int oldCardId) {
        this.oldCardId = oldCardId;
    }


    @Column(name="card_owner_id", nullable=false)
    public int getCardOwnerId() {
        return this.cardOwnerId;
    }
    
    public void setCardOwnerId(int cardOwnerId) {
        this.cardOwnerId = cardOwnerId;
    }


    @Column(name="seq", nullable=false)
    public int getSeq() {
        return this.seq;
    }
    
    public void setSeq(int seq) {
        this.seq = seq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OldCardId) ) return false;
		 OldCardId castOther = ( OldCardId ) other; 
         
		 return (this.getCardId()==castOther.getCardId())
 && (this.getOldCardId()==castOther.getOldCardId())
 && (this.getCardOwnerId()==castOther.getCardOwnerId())
 && (this.getSeq()==castOther.getSeq());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCardId();
         result = 37 * result + this.getOldCardId();
         result = 37 * result + this.getCardOwnerId();
         result = 37 * result + this.getSeq();
         return result;
   }   


}


