package com.ecard.core.model;
// Generated Oct 14, 2015 5:55:51 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OldCard generated by hbm2java
 */
@Entity
@Table(name="old_card"
)
public class OldCard  implements java.io.Serializable {


     private OldCardId id;
     private CardInfo cardInfo;

    public OldCard() {
    }

    public OldCard(OldCardId id, CardInfo cardInfo) {
       this.id = id;
       this.cardInfo = cardInfo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cardId", column=@Column(name="card_id", nullable=false) ), 
        @AttributeOverride(name="oldCardId", column=@Column(name="old_card_id", nullable=false) ), 
        @AttributeOverride(name="cardOwnerId", column=@Column(name="card_owner_id", nullable=false) ), 
        @AttributeOverride(name="seq", column=@Column(name="seq", nullable=false) ) } )
    public OldCardId getId() {
        return this.id;
    }
    
    public void setId(OldCardId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="card_id", nullable=false, insertable=false, updatable=false)
    public CardInfo getCardInfo() {
        return this.cardInfo;
    }
    
    public void setCardInfo(CardInfo cardInfo) {
        this.cardInfo = cardInfo;
    }




}


