package com.ecard.core.model;
// Generated Aug 4, 2015 10:15:08 AM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PossessionCard generated by hbm2java
 */
@Entity
@Table(name="possession_card"
)
public class PossessionCard  implements java.io.Serializable {


     private PossessionCardId id;
     private CardInfo cardInfo;
     private UserInfo userInfo;

    public PossessionCard() {
    }

    public PossessionCard(PossessionCardId id, CardInfo cardInfo, UserInfo userInfo) {
       this.id = id;
       this.cardInfo = cardInfo;
       this.userInfo = userInfo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="cardId", column=@Column(name="card_id", nullable=false) ), 
        @AttributeOverride(name="contactDate", column=@Column(name="contact_date", nullable=false, length=19) ), 
        @AttributeOverride(name="createDate", column=@Column(name="create_date", nullable=false, length=19) ) } )
    public PossessionCardId getId() {
        return this.id;
    }
    
    public void setId(PossessionCardId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="card_id", nullable=false, insertable=false, updatable=false)
    public CardInfo getCardInfo() {
        return this.cardInfo;
    }
    
    public void setCardInfo(CardInfo cardInfo) {
        this.cardInfo = cardInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }




}


