package com.ecard.core.model;
// Generated Aug 4, 2015 10:15:08 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PossessionCardId generated by hbm2java
 */
@Embeddable
public class PossessionCardId  implements java.io.Serializable {


     private int userId;
     private int cardId;
     private Date contactDate;
     private Date createDate;

    public PossessionCardId() {
    }

    public PossessionCardId(int userId, int cardId, Date contactDate, Date createDate) {
       this.userId = userId;
       this.cardId = cardId;
       this.contactDate = contactDate;
       this.createDate = createDate;
    }
   


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="card_id", nullable=false)
    public int getCardId() {
        return this.cardId;
    }
    
    public void setCardId(int cardId) {
        this.cardId = cardId;
    }


    @Column(name="contact_date", nullable=false, length=19)
    public Date getContactDate() {
        return this.contactDate;
    }
    
    public void setContactDate(Date contactDate) {
        this.contactDate = contactDate;
    }


    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PossessionCardId) ) return false;
		 PossessionCardId castOther = ( PossessionCardId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getCardId()==castOther.getCardId())
 && ( (this.getContactDate()==castOther.getContactDate()) || ( this.getContactDate()!=null && castOther.getContactDate()!=null && this.getContactDate().equals(castOther.getContactDate()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getCardId();
         result = 37 * result + ( getContactDate() == null ? 0 : this.getContactDate().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         return result;
   }   


}


