package com.ecard.core.model;
// Generated Aug 24, 2015 11:39:59 AM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PushInfo generated by hbm2java
 */
@Entity
@Table(name="push_info"
)
public class PushInfo  implements java.io.Serializable {


     private PushInfoId id;
     private UserInfo userInfo;

    public PushInfo() {
    }

    public PushInfo(PushInfoId id, UserInfo userInfo) {
       this.id = id;
       this.userInfo = userInfo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="deviceToken", column=@Column(name="device_token", nullable=false, length=65535) ), 
        @AttributeOverride(name="deviceType", column=@Column(name="device_type", nullable=false, length=65535) ), 
        @AttributeOverride(name="createDate", column=@Column(name="create_date", nullable=false, length=19) ), 
        @AttributeOverride(name="updateDate", column=@Column(name="update_date", nullable=false, length=19) ) } )
    public PushInfoId getId() {
        return this.id;
    }
    
    public void setId(PushInfoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }




}


