package com.ecard.core.model;
// Generated Aug 17, 2015 5:01:03 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles"
)
public class Roles  implements java.io.Serializable {


     private Integer roleId;
     private String roleName;
     private String permissionType;
     private Set<UserInfo> userInfos = new HashSet<UserInfo>(0);

    public Roles() {
    }

	
    public Roles(String permissionType) {
        this.permissionType = permissionType;
    }
    public Roles(String roleName, String permissionType, Set<UserInfo> userInfos) {
       this.roleName = roleName;
       this.permissionType = permissionType;
       this.userInfos = userInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="role_id", unique=true, nullable=false)
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    
    @Column(name="role_name", length=65535)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    
    @Column(name="permission_type", nullable=false, length=65535)
    public String getPermissionType() {
        return this.permissionType;
    }
    
	public void setPermissionType(String permissionType) {
        this.permissionType = permissionType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="roles")
    public Set<UserInfo> getUserInfos() {
        return this.userInfos;
    }
    
    public void setUserInfos(Set<UserInfo> userInfos) {
        this.userInfos = userInfos;
    }




}


