package com.ecard.core.model;
// Generated Sep 18, 2015 10:05:43 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;



/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name="user_info"
)
public class UserInfo  implements java.io.Serializable {


     private Integer userId;
     private TeamInfo teamInfo;
     private Roles roles;
     private Integer teamDivideCnt;
     private String email;
     private String password;
     private int mailSendFlg;
     private Integer mailNoticeFlg;
     private Integer mailUseAssistFlg;
     private Integer mailNewsFlg;
     private int groupDataDlFlg;
     private int allDataDlFlg;
     private int sfManualLinkFlg;
     private int groupDataDlRequestFlg;
     private int allDataDlRequestFlg;
     private String name;
     private String lastName;
     private String firstName;
     private String nameKana;
     private String lastNameKana;
     private String firstNameKana;
     private Integer groupCompanyId;
     private String companyName;
     private String companyNameKana;
     private String departmentName;
     private String positionName;
     private String zipCode;
     private String addressFull;
     private String address1;
     private String address2;
     private String address3;
     private String address4;
     private String telNumberCompany;
     private String telNumberDepartment;
     private String telNumberDirect;
     private String faxNumber;
     private String mobileNumber;
     private String companyUrl;
     private String coverImage;
     private String memo1;
     private String memo2;
     private int firstLoginF;
     private int leaveFlg;
     private int useStopFlg;
     private int helpdeskFlg;
     private int adminFlg;
     private Date lastLoginDate;
     private Date logoutDate;
     private Date createDate;
     private Date updateDate;
     private Integer operaterId;
     private Date deleteDate;
     private Integer deleteFlg;
     private Date lastChangePasswordDate;
     private Date useDate;
     private Date endDate;
     private String userIndexNo;
     private Integer roleAdminId;
     private Set<UserNotification> userNotifications = new HashSet<UserNotification>(0);
     private Set<UserCardMemo> userCardMemos = new HashSet<UserCardMemo>(0);
     private Set<PrusalHistory> prusalHistories = new HashSet<PrusalHistory>(0);
     private Set<AutoLogin> autoLogins = new HashSet<AutoLogin>(0);
     private UserSearch userSearch;
     private Set<DownloadCsv> downloadCsvs = new HashSet<DownloadCsv>(0);
     private Set<ActionLog> actionLogs = new HashSet<ActionLog>(0);
     private Set<UserTag> userTags = new HashSet<UserTag>(0);
     private Set<PossessionCard> possessionCards = new HashSet<PossessionCard>(0);
     private Set<PushInfo> pushInfos = new HashSet<PushInfo>(0);
     private Set<UserMigration> userMigrations = new HashSet<UserMigration>(0);
     private Set<InquiryInfo> inquiryInfos = new HashSet<InquiryInfo>(0);
     private Set<AdminPossessionCard> adminPossessionCards = new HashSet<AdminPossessionCard>(0);

    public UserInfo() {
    }

	
    public UserInfo(Roles roles, String email, String password, int mailSendFlg, int groupDataDlFlg, int allDataDlFlg, int sfManualLinkFlg, int groupDataDlRequestFlg, int allDataDlRequestFlg, int firstLoginF, int leaveFlg, int useStopFlg, int helpdeskFlg, int adminFlg) {
        this.roles = roles;
        this.email = email;
        this.password = password;
        this.mailSendFlg = mailSendFlg;
        this.groupDataDlFlg = groupDataDlFlg;
        this.allDataDlFlg = allDataDlFlg;
        this.sfManualLinkFlg = sfManualLinkFlg;
        this.groupDataDlRequestFlg = groupDataDlRequestFlg;
        this.allDataDlRequestFlg = allDataDlRequestFlg;
        this.firstLoginF = firstLoginF;
        this.leaveFlg = leaveFlg;
        this.useStopFlg = useStopFlg;
        this.helpdeskFlg = helpdeskFlg;
        this.adminFlg = adminFlg;
    }
    public UserInfo(TeamInfo teamInfo, Roles roles, Integer teamDivideCnt, String email, String password, int mailSendFlg, Integer mailNoticeFlg, Integer mailUseAssistFlg, Integer mailNewsFlg, int groupDataDlFlg, int allDataDlFlg, int sfManualLinkFlg, int groupDataDlRequestFlg, int allDataDlRequestFlg, String name, String lastName, String firstName, String nameKana, String lastNameKana, String firstNameKana, Integer groupCompanyId, String companyName, String companyNameKana, String departmentName, String positionName, String zipCode, String addressFull, String address1, String address2, String address3, String address4, String telNumberCompany, String telNumberDepartment, String telNumberDirect, String faxNumber, String mobileNumber, String companyUrl, String coverImage, String memo1, String memo2, int firstLoginF, int leaveFlg, int useStopFlg, int helpdeskFlg, int adminFlg, Date lastLoginDate, Date logoutDate, Date createDate, Date updateDate, Integer operaterId, Date deleteDate, Integer deleteFlg, Date lastChangePasswordDate, Date useDate, Date endDate, String userIndexNo, Integer roleAdminId, Set<UserNotification> userNotifications, Set<UserCardMemo> userCardMemos, Set<PrusalHistory> prusalHistories, Set<AutoLogin> autoLogins, UserSearch userSearch, Set<DownloadCsv> downloadCsvs, Set<ActionLog> actionLogs, Set<UserTag> userTags, Set<PossessionCard> possessionCards, Set<PushInfo> pushInfos, Set<UserMigration> userMigrations, Set<InquiryInfo> inquiryInfos, Set<AdminPossessionCard> adminPossessionCards) {
       this.teamInfo = teamInfo;
       this.roles = roles;
       this.teamDivideCnt = teamDivideCnt;
       this.email = email;
       this.password = password;
       this.mailSendFlg = mailSendFlg;
       this.mailNoticeFlg = mailNoticeFlg;
       this.mailUseAssistFlg = mailUseAssistFlg;
       this.mailNewsFlg = mailNewsFlg;
       this.groupDataDlFlg = groupDataDlFlg;
       this.allDataDlFlg = allDataDlFlg;
       this.sfManualLinkFlg = sfManualLinkFlg;
       this.groupDataDlRequestFlg = groupDataDlRequestFlg;
       this.allDataDlRequestFlg = allDataDlRequestFlg;
       this.name = name;
       this.lastName = lastName;
       this.firstName = firstName;
       this.nameKana = nameKana;
       this.lastNameKana = lastNameKana;
       this.firstNameKana = firstNameKana;
       this.groupCompanyId = groupCompanyId;
       this.companyName = companyName;
       this.companyNameKana = companyNameKana;
       this.departmentName = departmentName;
       this.positionName = positionName;
       this.zipCode = zipCode;
       this.addressFull = addressFull;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.address4 = address4;
       this.telNumberCompany = telNumberCompany;
       this.telNumberDepartment = telNumberDepartment;
       this.telNumberDirect = telNumberDirect;
       this.faxNumber = faxNumber;
       this.mobileNumber = mobileNumber;
       this.companyUrl = companyUrl;
       this.coverImage = coverImage;
       this.memo1 = memo1;
       this.memo2 = memo2;
       this.firstLoginF = firstLoginF;
       this.leaveFlg = leaveFlg;
       this.useStopFlg = useStopFlg;
       this.helpdeskFlg = helpdeskFlg;
       this.adminFlg = adminFlg;
       this.lastLoginDate = lastLoginDate;
       this.logoutDate = logoutDate;
       this.createDate = createDate;
       this.updateDate = updateDate;
       this.operaterId = operaterId;
       this.deleteDate = deleteDate;
       this.deleteFlg = deleteFlg;
       this.lastChangePasswordDate = lastChangePasswordDate;
       this.useDate = useDate;
       this.endDate = endDate;
       this.userIndexNo = userIndexNo;
       this.roleAdminId = roleAdminId;
       this.userNotifications = userNotifications;
       this.userCardMemos = userCardMemos;
       this.prusalHistories = prusalHistories;
       this.autoLogins = autoLogins;
       this.userSearch = userSearch;
       this.downloadCsvs = downloadCsvs;
       this.actionLogs = actionLogs;
       this.userTags = userTags;
       this.possessionCards = possessionCards;
       this.pushInfos = pushInfos;
       this.userMigrations = userMigrations;
       this.inquiryInfos = inquiryInfos;
       this.adminPossessionCards = adminPossessionCards;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="team_id")
    public TeamInfo getTeamInfo() {
        return this.teamInfo;
    }
    
    public void setTeamInfo(TeamInfo teamInfo) {
        this.teamInfo = teamInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id", nullable=false)
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }

    
    @Column(name="team_divide_cnt")
    public Integer getTeamDivideCnt() {
        return this.teamDivideCnt;
    }
    
    public void setTeamDivideCnt(Integer teamDivideCnt) {
        this.teamDivideCnt = teamDivideCnt;
    }

    
    @Column(name="email", nullable=false, length=65535)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=32)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="mail_send_flg", nullable=false)
    public int getMailSendFlg() {
        return this.mailSendFlg;
    }
    
    public void setMailSendFlg(int mailSendFlg) {
        this.mailSendFlg = mailSendFlg;
    }

    
    @Column(name="mail_notice_flg")
    public Integer getMailNoticeFlg() {
        return this.mailNoticeFlg;
    }
    
    public void setMailNoticeFlg(Integer mailNoticeFlg) {
        this.mailNoticeFlg = mailNoticeFlg;
    }

    
    @Column(name="mail_use_assist_flg")
    public Integer getMailUseAssistFlg() {
        return this.mailUseAssistFlg;
    }
    
    public void setMailUseAssistFlg(Integer mailUseAssistFlg) {
        this.mailUseAssistFlg = mailUseAssistFlg;
    }

    
    @Column(name="mail_news_flg")
    public Integer getMailNewsFlg() {
        return this.mailNewsFlg;
    }
    
    public void setMailNewsFlg(Integer mailNewsFlg) {
        this.mailNewsFlg = mailNewsFlg;
    }

    
    @Column(name="group_data_dl_flg", nullable=false)
    public int getGroupDataDlFlg() {
        return this.groupDataDlFlg;
    }
    
    public void setGroupDataDlFlg(int groupDataDlFlg) {
        this.groupDataDlFlg = groupDataDlFlg;
    }

    
    @Column(name="all_data_dl_flg", nullable=false)
    public int getAllDataDlFlg() {
        return this.allDataDlFlg;
    }
    
    public void setAllDataDlFlg(int allDataDlFlg) {
        this.allDataDlFlg = allDataDlFlg;
    }

    
    @Column(name="sf_manual_link_flg", nullable=false)
    public int getSfManualLinkFlg() {
        return this.sfManualLinkFlg;
    }
    
    public void setSfManualLinkFlg(int sfManualLinkFlg) {
        this.sfManualLinkFlg = sfManualLinkFlg;
    }

    
    @Column(name="group_data_dl_request_flg", nullable=false)
    public int getGroupDataDlRequestFlg() {
        return this.groupDataDlRequestFlg;
    }
    
    public void setGroupDataDlRequestFlg(int groupDataDlRequestFlg) {
        this.groupDataDlRequestFlg = groupDataDlRequestFlg;
    }

    
    @Column(name="all_data_dl_request_flg", nullable=false)
    public int getAllDataDlRequestFlg() {
        return this.allDataDlRequestFlg;
    }
    
    public void setAllDataDlRequestFlg(int allDataDlRequestFlg) {
        this.allDataDlRequestFlg = allDataDlRequestFlg;
    }

    
    @Column(name="name", length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="last_name", length=65535)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="first_name", length=65535)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="name_kana", length=65535)
    public String getNameKana() {
        return this.nameKana;
    }
    
    public void setNameKana(String nameKana) {
        this.nameKana = nameKana;
    }

    
    @Column(name="last_name_kana", length=65535)
    public String getLastNameKana() {
        return this.lastNameKana;
    }
    
    public void setLastNameKana(String lastNameKana) {
        this.lastNameKana = lastNameKana;
    }

    
    @Column(name="first_name_kana", length=65535)
    public String getFirstNameKana() {
        return this.firstNameKana;
    }
    
    public void setFirstNameKana(String firstNameKana) {
        this.firstNameKana = firstNameKana;
    }

    
    @Column(name="group_company_id")
    public Integer getGroupCompanyId() {
        return this.groupCompanyId;
    }
    
    public void setGroupCompanyId(Integer groupCompanyId) {
        this.groupCompanyId = groupCompanyId;
    }

    
    @Column(name="company_name", length=65535)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    
    @Column(name="company_name_kana", length=65535)
    public String getCompanyNameKana() {
        return this.companyNameKana;
    }
    
    public void setCompanyNameKana(String companyNameKana) {
        this.companyNameKana = companyNameKana;
    }

    
    @Column(name="department_name", length=65535)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    
    @Column(name="position_name", length=65535)
    public String getPositionName() {
        return this.positionName;
    }
    
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    
    @Column(name="zip_code", length=65535)
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    
    @Column(name="address_full", length=65535)
    public String getAddressFull() {
        return this.addressFull;
    }
    
    public void setAddressFull(String addressFull) {
        this.addressFull = addressFull;
    }

    
    @Column(name="address_1", length=65535)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    
    @Column(name="address_2", length=65535)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="address_3", length=65535)
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    
    @Column(name="address_4", length=65535)
    public String getAddress4() {
        return this.address4;
    }
    
    public void setAddress4(String address4) {
        this.address4 = address4;
    }

    
    @Column(name="tel_number_company", length=65535)
    public String getTelNumberCompany() {
        return this.telNumberCompany;
    }
    
    public void setTelNumberCompany(String telNumberCompany) {
        this.telNumberCompany = telNumberCompany;
    }

    
    @Column(name="tel_number_department", length=65535)
    public String getTelNumberDepartment() {
        return this.telNumberDepartment;
    }
    
    public void setTelNumberDepartment(String telNumberDepartment) {
        this.telNumberDepartment = telNumberDepartment;
    }

    
    @Column(name="tel_number_direct", length=65535)
    public String getTelNumberDirect() {
        return this.telNumberDirect;
    }
    
    public void setTelNumberDirect(String telNumberDirect) {
        this.telNumberDirect = telNumberDirect;
    }

    
    @Column(name="fax_number", length=65535)
    public String getFaxNumber() {
        return this.faxNumber;
    }
    
    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }

    
    @Column(name="mobile_number", length=65535)
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    
    @Column(name="company_url", length=65535)
    public String getCompanyUrl() {
        return this.companyUrl;
    }
    
    public void setCompanyUrl(String companyUrl) {
        this.companyUrl = companyUrl;
    }

    
    @Column(name="cover_image", length=65535)
    public String getCoverImage() {
        return this.coverImage;
    }
    
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage;
    }

    
    @Column(name="memo1", length=65535)
    public String getMemo1() {
        return this.memo1;
    }
    
    public void setMemo1(String memo1) {
        this.memo1 = memo1;
    }

    
    @Column(name="memo2", length=65535)
    public String getMemo2() {
        return this.memo2;
    }
    
    public void setMemo2(String memo2) {
        this.memo2 = memo2;
    }

    
    @Column(name="first_login_f", nullable=false)
    public int getFirstLoginF() {
        return this.firstLoginF;
    }
    
    public void setFirstLoginF(int firstLoginF) {
        this.firstLoginF = firstLoginF;
    }

    
    @Column(name="leave_flg", nullable=false)
    public int getLeaveFlg() {
        return this.leaveFlg;
    }
    
    public void setLeaveFlg(int leaveFlg) {
        this.leaveFlg = leaveFlg;
    }

    
    @Column(name="use_stop_flg", nullable=false)
    public int getUseStopFlg() {
        return this.useStopFlg;
    }
    
    public void setUseStopFlg(int useStopFlg) {
        this.useStopFlg = useStopFlg;
    }

    
    @Column(name="helpdesk_flg", nullable=false)
    public int getHelpdeskFlg() {
        return this.helpdeskFlg;
    }
    
    public void setHelpdeskFlg(int helpdeskFlg) {
        this.helpdeskFlg = helpdeskFlg;
    }

    
    @Column(name="admin_flg", nullable=false)
    public int getAdminFlg() {
        return this.adminFlg;
    }
    
    public void setAdminFlg(int adminFlg) {
        this.adminFlg = adminFlg;
    }

    
    @Column(name="last_login_date", length=19)
    public Date getLastLoginDate() {
        return this.lastLoginDate;
    }
    
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    
    @Column(name="logout_date", length=19)
    public Date getLogoutDate() {
        return this.logoutDate;
    }
    
    public void setLogoutDate(Date logoutDate) {
        this.logoutDate = logoutDate;
    }

    
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="operater_id")
    public Integer getOperaterId() {
        return this.operaterId;
    }
    
    public void setOperaterId(Integer operaterId) {
        this.operaterId = operaterId;
    }

    
    @Column(name="delete_date", length=19)
    public Date getDeleteDate() {
        return this.deleteDate;
    }
    
    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }

    
    @Column(name="delete_flg")
    public Integer getDeleteFlg() {
        return this.deleteFlg;
    }
    
    public void setDeleteFlg(Integer deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    
    @Column(name="last_change_password_date", length=19)
    public Date getLastChangePasswordDate() {
        return this.lastChangePasswordDate;
    }
    
    public void setLastChangePasswordDate(Date lastChangePasswordDate) {
        this.lastChangePasswordDate = lastChangePasswordDate;
    }

    
    @Column(name="use_date", length=19)
    public Date getUseDate() {
        return this.useDate;
    }
    
    public void setUseDate(Date useDate) {
        this.useDate = useDate;
    }

    
    @Column(name="end_date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="user_index_no", length=18)
    public String getUserIndexNo() {
        return this.userIndexNo;
    }
    
    public void setUserIndexNo(String userIndexNo) {
        this.userIndexNo = userIndexNo;
    }

    
    @Column(name="role_admin_id")
    public Integer getRoleAdminId() {
        return this.roleAdminId;
    }
    
    public void setRoleAdminId(Integer roleAdminId) {
        this.roleAdminId = roleAdminId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userInfo")
    public Set<UserNotification> getUserNotifications() {
        return this.userNotifications;
    }
    
    public void setUserNotifications(Set<UserNotification> userNotifications) {
        this.userNotifications = userNotifications;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userInfo")
    public Set<UserCardMemo> getUserCardMemos() {
        return this.userCardMemos;
    }
    
    public void setUserCardMemos(Set<UserCardMemo> userCardMemos) {
        this.userCardMemos = userCardMemos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userInfo")
    public Set<PrusalHistory> getPrusalHistories() {
        return this.prusalHistories;
    }
    
    public void setPrusalHistories(Set<PrusalHistory> prusalHistories) {
        this.prusalHistories = prusalHistories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userInfo")
    public Set<AutoLogin> getAutoLogins() {
        return this.autoLogins;
    }
    
    public void setAutoLogins(Set<AutoLogin> autoLogins) {
        this.autoLogins = autoLogins;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="userInfo")
    public UserSearch getUserSearch() {
        return this.userSearch;
    }
    
    public void setUserSearch(UserSearch userSearch) {
        this.userSearch = userSearch;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userInfo")
    public Set<DownloadCsv> getDownloadCsvs() {
        return this.downloadCsvs;
    }
    
    public void setDownloadCsvs(Set<DownloadCsv> downloadCsvs) {
        this.downloadCsvs = downloadCsvs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userInfo")
    public Set<ActionLog> getActionLogs() {
        return this.actionLogs;
    }
    
    public void setActionLogs(Set<ActionLog> actionLogs) {
        this.actionLogs = actionLogs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userInfo")
    public Set<UserTag> getUserTags() {
        return this.userTags;
    }
    
    public void setUserTags(Set<UserTag> userTags) {
        this.userTags = userTags;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userInfo")
    public Set<PossessionCard> getPossessionCards() {
        return this.possessionCards;
    }
    
    public void setPossessionCards(Set<PossessionCard> possessionCards) {
        this.possessionCards = possessionCards;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userInfo")
    public Set<PushInfo> getPushInfos() {
        return this.pushInfos;
    }
    
    public void setPushInfos(Set<PushInfo> pushInfos) {
        this.pushInfos = pushInfos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userInfo")
    public Set<UserMigration> getUserMigrations() {
        return this.userMigrations;
    }
    
    public void setUserMigrations(Set<UserMigration> userMigrations) {
        this.userMigrations = userMigrations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userInfo")
    public Set<InquiryInfo> getInquiryInfos() {
        return this.inquiryInfos;
    }
    
    public void setInquiryInfos(Set<InquiryInfo> inquiryInfos) {
        this.inquiryInfos = inquiryInfos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userInfo")
    public Set<AdminPossessionCard> getAdminPossessionCards() {
        return this.adminPossessionCards;
    }
    
    public void setAdminPossessionCards(Set<AdminPossessionCard> adminPossessionCards) {
        this.adminPossessionCards = adminPossessionCards;
    }




}


