package com.ecard.core.model;
// Generated Aug 4, 2015 10:15:08 AM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserTag generated by hbm2java
 */
@Entity
@Table(name="user_tag"
)
public class UserTag  implements java.io.Serializable {


     private Integer tagId;
     private UserInfo userInfo;
     private String tagName;
     private Set<CardTag> cardTags = new HashSet<CardTag>(0);

    public UserTag() {
    }

	
    public UserTag(String tagName) {
        this.tagName = tagName;
    }
    public UserTag(UserInfo userInfo, String tagName, Set<CardTag> cardTags) {
       this.userInfo = userInfo;
       this.tagName = tagName;
       this.cardTags = cardTags;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tag_id", unique=true, nullable=false)
    public Integer getTagId() {
        return this.tagId;
    }
    
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }

    
    @Column(name="tag_name", nullable=false, length=65535)
    public String getTagName() {
        return this.tagName;
    }
    
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userTag")
    public Set<CardTag> getCardTags() {
        return this.cardTags;
    }
    
    public void setCardTags(Set<CardTag> cardTags) {
        this.cardTags = cardTags;
    }




}


