package com.ecard.core.model;
// Generated Jul 29, 2015 9:53:05 AM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserSearchId generated by hbm2java
 */
@Embeddable
public class UserSearchId  implements java.io.Serializable {


     private int userId;
     private String title;
     private String searchText;
     private String memo;

    public UserSearchId() {
    }

	
    public UserSearchId(int userId, String title, String searchText) {
        this.userId = userId;
        this.title = title;
        this.searchText = searchText;
    }
    public UserSearchId(int userId, String title, String searchText, String memo) {
       this.userId = userId;
       this.title = title;
       this.searchText = searchText;
       this.memo = memo;
    }
   


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="title", nullable=false, length=65535)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }


    @Column(name="search_text", nullable=false, length=65535)
    public String getSearchText() {
        return this.searchText;
    }
    
    public void setSearchText(String searchText) {
        this.searchText = searchText;
    }


    @Column(name="memo", length=65535)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserSearchId) ) return false;
		 UserSearchId castOther = ( UserSearchId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && ( (this.getTitle()==castOther.getTitle()) || ( this.getTitle()!=null && castOther.getTitle()!=null && this.getTitle().equals(castOther.getTitle()) ) )
 && ( (this.getSearchText()==castOther.getSearchText()) || ( this.getSearchText()!=null && castOther.getSearchText()!=null && this.getSearchText().equals(castOther.getSearchText()) ) )
 && ( (this.getMemo()==castOther.getMemo()) || ( this.getMemo()!=null && castOther.getMemo()!=null && this.getMemo().equals(castOther.getMemo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + ( getTitle() == null ? 0 : this.getTitle().hashCode() );
         result = 37 * result + ( getSearchText() == null ? 0 : this.getSearchText().hashCode() );
         result = 37 * result + ( getMemo() == null ? 0 : this.getMemo().hashCode() );
         return result;
   }   


}


