package com.ecard.core.model;
// Generated Aug 19, 2015 2:57:55 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserSearch generated by hbm2java
 */
@Entity
@Table(name="user_search"
)
public class UserSearch  implements java.io.Serializable {

     private Integer userId;
     private UserInfo userInfo;
     private String title;
     private String freeText;
     private String owner;
     private String company;
     private String department;
     private String position;
     private String name;
     private int seq;
     private int parameterFlg;

    public UserSearch() {
    }

    public UserSearch(UserInfo userInfo, String title, String freeText, String owner, String company, String department, String position, String name, int seq, int parameterFlg) {
       this.userInfo = userInfo;
       this.title = title;
       this.freeText = freeText;
       this.owner = owner;
       this.company = company;
       this.department = department;
       this.position = position;
       this.name = name;
       this.seq = seq;
       this.parameterFlg = parameterFlg;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="userInfo"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }

    
    @Column(name="title", nullable=false, length=65535)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="free_text", nullable=false, length=65535)
    public String getFreeText() {
        return this.freeText;
    }
    
    public void setFreeText(String freeText) {
        this.freeText = freeText;
    }

    
    @Column(name="owner", nullable=false, length=65535)
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }

    
    @Column(name="company", nullable=false, length=65535)
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    
    @Column(name="department", nullable=false, length=65535)
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }

    
    @Column(name="position", nullable=false, length=65535)
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    
    @Column(name="name", nullable=false, length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="seq", nullable=false)
    public int getSeq() {
        return this.seq;
    }
    
    public void setSeq(int seq) {
        this.seq = seq;
    }

    @Column(name="parameter_flg", nullable=false)
    public int getParameterFlg() {
        return this.parameterFlg;
    }
    
    public void setParameterFlg(int parameterFlg) {
        this.parameterFlg = parameterFlg;
    }
    


}


