package com.ecard.core.model;
// Generated Aug 4, 2015 10:15:08 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserCardMemoId generated by hbm2java
 */
@Embeddable
public class UserCardMemoId  implements java.io.Serializable {


     private int userId;
     private int cardId;
     private String memo;
     private int seq;
     private Date createDate;

    public UserCardMemoId() {
    }

	
    public UserCardMemoId(int userId, int cardId, int seq, Date createDate) {
        this.userId = userId;
        this.cardId = cardId;
        this.seq = seq;
        this.createDate = createDate;
    }
    public UserCardMemoId(int userId, int cardId, String memo, int seq, Date createDate) {
       this.userId = userId;
       this.cardId = cardId;
       this.memo = memo;
       this.seq = seq;
       this.createDate = createDate;
    }
   


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


    @Column(name="card_id", nullable=false)
    public int getCardId() {
        return this.cardId;
    }
    
    public void setCardId(int cardId) {
        this.cardId = cardId;
    }


    @Column(name="memo", length=65535)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }


    @Column(name="seq", nullable=false)
    public int getSeq() {
        return this.seq;
    }
    
    public void setSeq(int seq) {
        this.seq = seq;
    }


    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserCardMemoId) ) return false;
		 UserCardMemoId castOther = ( UserCardMemoId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getCardId()==castOther.getCardId())
 && ( (this.getMemo()==castOther.getMemo()) || ( this.getMemo()!=null && castOther.getMemo()!=null && this.getMemo().equals(castOther.getMemo()) ) )
 && (this.getSeq()==castOther.getSeq())
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getCardId();
         result = 37 * result + ( getMemo() == null ? 0 : this.getMemo().hashCode() );
         result = 37 * result + this.getSeq();
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         return result;
   }   


}


